### ISSUE TITLE
Extension is related to issue

### ISSUE THREAD

**Issue by Cyclodex** [garaio/vscode-unwanted-recommendations#1]
This extension was built, after some findings and checking discussions mostly over at: https://github.com/microsoft/vscode/issues/40239#issuecomment-1375910194

And currently we are discussing profile improvements, regarding missing extension features over here: https://github.com/microsoft/vscode/issues/170916

**Comment by iyerusad** [comment]
Hopefully a good issue to subscribe to be alerted on updates related to this extension no longer being needed (or possible drastic behavior change).

Thanks @Cyclodex 🥳🥳🎉🎉 for putting this together, used initially for Vue/Volar scenario

**Comment by Cyclodex** [comment]
Yes, exactly.

Currently we are discussing missing functionality in the profiles feature over here https://github.com/microsoft/vscode/issues/170916

**Comment by Cyclodex** [comment]
⚠️ This repo and extension is not maintained anymore (deprecated), please continue follow the successor over here:
https://github.com/SoulcodeAgency/vscode-unwanted-extensions/issues/3
