### ISSUE TITLE
extension cause high cpu

### ISSUE THREAD

**Issue by tjx666** [garaio/vscode-unwanted-recommendations#2]
After I enable this extension:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/41773861/218274445-2337fe50-8c95-4e47-93fd-b375ea091912.png">

Seems this extension call rg and cause it

```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by Cyclodex** [comment]
Thx for reporting, lets check why this is happening... any help or ideas are welcome

**Comment by Cyclodex** [comment]
https://github.com/microsoft/vscode/issues/98594#issue-624977400

**Comment by Cyclodex** [comment]
@tjx666 cant reproduce it yet, neither on windows or mac. Can you help identify the issue, why do you think the issue is related to the extension? Could it be anything else on your system? Please check the attached vscode issue above as well.
Thx for your help

Maybe you check the vscode "help -> process explorer" to further identify the issue?

**Comment by tjx666** [comment]
https://user-images.githubusercontent.com/41773861/218311621-f636e184-5452-48f2-998e-a54112bf5a42.mov

<img width="706" alt="image" src="https://user-images.githubusercontent.com/41773861/218311679-85596a3a-8825-4d9b-867d-0cc836548643.png">

**Comment by Cyclodex** [comment]
Thx! Do you have a .vscode/extensions.json file or not? Looks like vscode has an issue with the file activator, hmm

**Comment by tjx666** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/218312726-8e296fae-a413-4596-812d-1c10e4050f6c.png">


```json
{
    "recommendations": [
        "andersonbruceb.json-in-html",
        "antfu.file-nesting",
        "DavidAnson.vscode-markdownlint",
        "dbaeumer.vscode-eslint",
        "dzhavat.css-initial-value",
        "eamodio.gitlens",
        "esbenp.prettier-vscode",
        "pflannery.vscode-versionlens",
        "streetsidesoftware.code-spell-checker",
        "stylelint.vscode-stylelint",
        "Vue.volar",
        "YuTengjing.vscode-neo-file-utils",
        "zyrong.node-modules",
        // 使用 take over mode 可以不装，https://github.com/johnsoncodehk/volar/discussions/471
        "Vue.vscode-typescript-vue-plugin",
        "vunguyentuan.vscode-css-variables"
    ],
    "unwantedRecommendations": [
        // 和 volar 冲突
        "octref.vetur"
    ]
}
```

**Comment by Cyclodex** [comment]
@tjx666 does the following mentioned setting have an impact on your scenario?
> "search.followSymlinks": false
https://github.com/microsoft/vscode/issues/98594#issuecomment-658533647

I have no idea why vscode has an issue with finding the `.vscode/extensions.json` file on your machine...
This just comes from the default activation setting I have set, and looks good in my eyes

```json
"activationEvents": [
    "workspaceContains:.vscode/extensions.json"
  ],
```
which should be correct as documented here: https://code.visualstudio.com/api/references/activation-events#workspaceContains

If you have the time, can you try the same thing with deleted node_modules, I read that sometimes lots of files and stuff  from node modules make troubles with search, but maybe the search setting already helped you...

**Comment by Cyclodex** [comment]
Until no further help or investigation or reproduction, I can't help with this issue.
