### ISSUE TITLE
Does it not work in a multi-root workspace?

### ISSUE THREAD

**Issue by thany** [garaio/vscode-unwanted-recommendations#3]
I added some `unwantedRecommendations` for one of the roots in my workspace, and as soon as I install this extension, it immediately displays a notification:

> ⚠ No defined extensions found, please define "unwantedRecommendations" within the ".vscode/extensions.json" file. See [documentation](https://github.com/garaio/vscode-unwanted-recommendations) for more details.

This notification also pops up when a project or workspace is loaded that *genuinely* doesn't have counter-recommendations like this, which might be annoying whenever switching to another project or workspace.

Structure is kind of like this:

```
[workspace]
|- Root 1
|- Root 2
\- Root 3
   \- .vscode
      |- settings.json
      \- extensions.json
```

In the extensions.json, it's just a simple matter of:

```json
{
  // These extensions are super niiice for this project
  "recommendations": [
    // ...
  ],

  // These extensions can throw a wrench in the works
  "unwantedRecommendations": [
    "hookyqr.beautify"
    // ...
  ]
}
```

Nothing much going on there. I'm assuming it's okay to use jsonc format with a `.json` file extension, as VSCode isn't complaining.

**Comment by Cyclodex** [comment]
Hi, I did not yet work with multi root workspaces, but I tried to read into it right now.

I don't think that VS Code would support something like that, as you have described above. I mean the extensions file within the root folder, this setup is not supported for multi roots.
I tested this, and the extensions are not showing up as "@recommended".

However there are other possible ways how to support multi root setups:

1. Move your `.vscode` folder with the `extensions.json` file to your `code-workspace`-file, this should make it already work with the current version of this extension.
![image](https://user-images.githubusercontent.com/840929/221018449-cab7bd65-74ab-44a8-83e3-60838e22108c.png)

2. I did read in the documentation, that settings can also be defined within the `code-workspace`-file. This extension is not yet reading this out. I can add this as a feature request, I think this should be possible.
![image](https://user-images.githubusercontent.com/840929/221019850-0bc5ae32-cfeb-45c7-8f73-eed9f5b58c70.png)

  - Check for *.code-workspace`-file/s
  - Check for the defined extensions in there and run the extension as already doing with the default `.vscode/extensions.json` setup

----

@thany What do you think?
- Does point 1 work for you?
- Would you prefer to have the feature as described in point 2 within the code-workspace file?

Documentation about the multi-root workspaces:

- https://code.visualstudio.com/docs/editor/workspaces
- https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by Cyclodex** [comment]
@thany check out the latest release 0.4.0 - I added support to configure the extensions in the `code-workspace`-settings file, and lowered the verbosity of some messages.

Let me know if we can close this task, or if there is still something you would like to see addressed in this topic.

See [Workspaces / Multi-root workspaces section in the README](https://github.com/garaio/vscode-unwanted-recommendations#requirements)

**Comment by thany** [comment]
That's halfway there, it seems 😉

Defining these settings in the workspace, will indeed enable them for the workspace, but for *every* root in the workspace. I was kinda hoping to have extensions (dis)recommended on a per-root basis within one workspace.

After reading your reply, I'm not not entirely sure that VSCode can support this actually. I hope so, but as an extension developer, maybe you have a deeper understanding of this sort of thing than I do.

**Comment by Cyclodex** [comment]
I would not know how... but this was my first extension so i am not (yet) master of extensions :)
I think you would have to open every root separately in a new vscode instance, then it will work independently. But i would not know how this would be possible as a workspace with multiple roots.

But if someone knows better, please tell us :)

**Comment by Cyclodex** [comment]
> Version 0.4.0: I added support to configure the extensions in the code-workspace-settings file

As mentioned above, I will close this ticket, as we have done what is possible right now.
Feel free to open new more specific tickets.
