### ISSUE TITLE
Deprecating repository

### ISSUE THREAD

**Issue by Cyclodex** [garaio/vscode-unwanted-recommendations#5]
Hi

As synced with Jörg B., it's okey that I take over the extension and repo to continue maintaining the extension.

However, the VS Code extensions can not yet be migrated across **publishers**, therefor I placed a request within the issue here (https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-8022245), where it should get handled.

I created a new extension based on the fork from this repo here.

* https://github.com/SoulcodeAgency/vscode-unwanted-extensions
* https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions

Please merge the PR I created ( #4 ) to make it more clear to the github repo as well.

I think that's all right now, otherwise I will let you know.

Thanks a lot

**Comment by hightow** [comment]
PR is merged!
